version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./phpventas:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - pgsql

  pgsql:
    image: postgres:11.19-alpine
    container_name: pgsql
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      POSTGRES_DB: ventasweb1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
